import "./infoPage.css";
import { useState, useEffect } from "react";

import ParallaxSection from './ParallaxSection';
import Navbar from './NavBar';
import heroImage from '../../assets/hero.jpg';
import biomassImage from '../../assets/food.jpg';
import biodigesterImage from '../../assets/biogas.jpg';
import certificadoImage from '../../assets/certificado.jpg';
import syngasImage from '../../assets/syngas.jpg';
import psaImage from '../../assets/psa-system.jpg';
import fuelCellImage from '../../assets/fuel-cell.jpg';
import automationImage from '../../assets/automation-control.jpg';
import aiImage from '../../assets/ai-machine-learning.jpg';
import bike from '../../assets/bike.jpg';
import amonia from '../../assets/amonia.jpg';

import VideoMiniPlayer from "./VideoMiniPlayer";

export default function HydrogenProduction() {
  const [lang, setLang] = useState(localStorage.getItem('app_lang') || 'pt');

  useEffect(() => {
    const handler = (e) => setLang(e?.detail || localStorage.getItem('app_lang') || 'pt');
    window.addEventListener('langChange', handler);
    return () => window.removeEventListener('langChange', handler);
  }, []);

  const texts = {
    hero: {
      pt: {
        title: "Projeto B2H2: Produção e Usos do Hidrogênio Renovável em Escala Piloto",
        subtitle: "OBTENÇÃO DE H\u2082 DE ALTA PUREZA, SEM USO DE ÁGUA E COM BAIXA EMISSÃO DE CARBONO, A PARTIR DE RESÍDUOS DE ALIMENTOS",
        desc: "Conheça o projeto B2H2 (Biogas-to-Hydrogen): a primeira planta piloto do Brasil dedicada à produção de hidrogênio renovável de alta pureza a partir do biogás de resíduos orgânicos, em um processo inovador que dispensa o uso de água e minimiza a pegada de carbono. O sistema integra módulos avançados — conversão termoquímica, purificação via PSA, armazenamento, e conversão em eletricidade por Células a Combustível — com aplicações demonstrativas em Amônia e Mobilidade Urbana. Toda a operação é controlada por um sistema de automação com apoio de Inteligência Artificial na gestão de dados e otimização dos processos."
      },
      en: {
        title: "B2H2 Project: Production and Uses of Renewable Hydrogen at Pilot Scale",
        subtitle: "PRODUCTION OF HIGH-PURITY H\u2082 WITHOUT WATER USE AND LOW CARBON EMISSIONS, FROM FOOD WASTE",
        desc: "Meet B2H2 (Biogas-to-Hydrogen): Brazil's pilot plant for producing high-purity renewable hydrogen from biogas generated by organic waste, using an innovative water-free process with low carbon footprint. The system integrates advanced modules — thermochemical conversion, PSA purification, storage, and electricity generation via fuel cells — with demonstration uses in ammonia and urban mobility. The operation is managed by an automation system with AI for data handling and process optimization."
      }
    },
    biomassa: {
      pt: {
        title: "Origem da Biomassa",
        desc: "O Restaurante Universitário (RU) da UFPR atende toda a comunidade universitária, e serve diariamente cerca de 14.000 refeições, entre café da manhã, almoço e jantar, no modelo self-service. O grande volume de refeições acaba gerando certa quantidade de resíduos orgânicos (alimentos) com potencial para a produção de biogás. A planta piloto - B2H2, recebe parte destes resíduos devidamente processados para conversão em biogás por meio da biodigestão anaeróbia."
      },
      en: {
        title: "Origin of Biomass",
        desc: "The University Restaurant (RU) at UFPR serves the university community, providing around 14,000 meals daily, including breakfast, lunch, and dinner, in a self-service model. This large volume of meals generates a certain amount of organic waste (food) with potential for biogas production. The pilot plant - B2H2, receives some of this waste properly processed for conversion into biogas through anaerobic digestion."
      }
    },
    biodigestor: {
      pt: { title: "Biodigestão Anaeróbia - Biogás", desc: "Os resíduos de alimentos do RU são submetidos ao processo de biodigestão anaeróbia, que compreende ciclos fundamentais como hidrólise, acidogênese, acetogênese e metanogênese, gerando o biogás, um recurso energético amplamente empregado como insumo para a produção de energia, que consiste, principalmente, em uma mistura de metano (CH\u2084) e dióxido de carbono (CO\u2082). Para o projeto B2H2, foi desenvolvido um sistema de biodigestão inovador, que permite tratar os resíduos de  maneira contínua com elevada eficiência." },
      en: { title: "Anaerobic Biodigestion - Biogas", desc: "The RU food waste undergoes anaerobic biodigestion, which includes fundamental cycles such as hydrolysis, acidogenesis, acetogenesis, and methanogenesis, generating biogas, an energy resource widely used as a feedstock for energy production, consisting mainly of a mixture of methane (CH\u2084) and carbon dioxide (CO\u2082). For the B2H2 project, an innovative biodigestion system was developed, allowing continuous treatment of waste with high efficiency." }
    },
    syngas: {
      pt: { title: "Produção de Syngas", desc: "O biogás (mistura de CH\u2084 e CO\u2082) é submetido a um processo termoquímico a 800°C na presença de um catalisador, desenvolvido exclusivamente para o projeto B2H2, capaz de convertê-lo em syngas (gás de síntese), que consiste em um mistura gasosa de hidrogênio (H\u2082) e monóxido de carbo o (CO). O syngas que se caracteriza como matéria prima para a produção de vários produtos de interesse industrial (metanol, BioQAv, etc) ou para o fornecimento do hidrogênio, quando este é separado e purificado." },
      en: { title: "Syngas Production", desc: "Biogas (CH\u2084 and CO\u2082 mix) undergoes a thermochemical process at 800°C in the presence of a catalyst, developed exclusively for the B2H2 project, capable of converting it into syngas (synthesis gas), which is a gaseous mixture of hydrogen (H\u2082) and carbon monoxide (CO). The syngas is characterized as a raw material for producing various industrially relevant products (methanol, BioQAv, etc.) or for supplying hydrogen, when it is separated and purified." }
    },
    psa: {
      pt: { title: "Hidrogênio Renovável de Alta Pureza", desc: "O processo de Pressure Swing Adsorption (PSA) é responsável pela purificação do hidrogênio por meio da adsorção seletiva de impurezas em materiais porosos, como zeólitas ou peneiras moleculares. Durante as etapas de pressurização e despressurização, o sistema remove o CO, resultando em hidrogênio com pureza superior a 99,99%, adequado para uso em células a combustível do tipo PEM, onde a presença de contaminantes pode comprometer o desempenho e a durabilidade do sistema eletroquímico." },
      en: { title: "High-Purity Renewable Hydrogen", desc: "The Pressure Swing Adsorption (PSA) process is responsible for purifying hydrogen through the selective adsorption of impurities onto porous materials, such as zeolites or molecular sieves. During the pressurization and depressurization stages, the system removes CO, resulting in hydrogen with a purity greater than 99.99%, suitable for use in PEM fuel cells, where the presence of contaminants can compromise the performance and durability of the electrochemical system." }
    },
    fuelcell: {
      pt: { title: "Célula a Combustível PEM", desc: "O sistema de geração de energia a hidrogênio do Campus Politécnico da UFPR baseia-se em células a combustível do tipo PEM (Proton Exchange Membrane). O hidrogênio, previamente purificado e armazenado em cilindros, alimenta duas células PEM de 2,5 kW cada. No interior das células, o hidrogênio reage eletroquimicamente com o oxigênio do ar, gerando eletricidade, calor e água como único subproduto, sem emissão de poluentes. A potência produzida é regulada por um banco de baterias que armazena e estabiliza a energia, garantindo fornecimento contínuo e ajustando a potência instantânea. A corrente contínua (CC) proveniente das células e baterias é então convertida em corrente alternada (CA) por dois inversores. Por fim, a energia elétrica gerada é integrada à rede do Campus, demonstrando o potencial do uso sustentável de fontes limpas de energia." },
      en: { title: "PEM Fuel Cell", desc: "The hydrogen energy generation system at the Polytechnic Campus of UFPR is based on PEM (Proton Exchange Membrane) fuel cells. The hydrogen, previously purified and stored in cylinders, feeds two 2.5 kW PEM cells. Inside the cells, hydrogen electrochemically reacts with oxygen from the air, generating electricity, heat, and water as the only byproduct, without pollutant emissions. The produced power is regulated by a battery bank that stores and stabilizes the energy, ensuring continuous supply and adjusting the instantaneous power. The direct current (DC) from the cells and batteries is then converted to alternating current (AC) by two inverters. Finally, the generated electric energy is integrated into the Campus grid, demonstrating the potential of sustainable use of clean energy sources." }
    },
    amonia: {
      pt: { title: "Amônia Renovável", desc: "O hidrogênio de alta pureza produzido na planta B2H2 é um insumo essencial para a síntese da amônia (NH\u2083) renovável, sendo um dos principais vetores de energia junto ao hidrogênio. A amônia renovável é crucial para a descarbonização de setores como a agricultura (fertilizantes) e o transporte marítimo (combustível), e o projeto B2H2 demonstra como o hidrogênio renovável, obtido de resíduos orgânicos, pode alimentar essa importante cadeia de valor industrial, promovendo uma economia circular e sustentável." },
      en: { title: "Renewable Ammonia", desc: "The high-purity hydrogen produced at B2H2 is a key input for the synthesis of renewable ammonia (NH\u2083), being one of the main energy vectors alongside hydrogen. Renewable ammonia is crucial for the decarbonization of sectors such as agriculture (fertilizers) and maritime transport (fuel), and the B2H2 project demonstrates how renewable hydrogen, obtained from organic waste, can fuel this important industrial value chain, promoting a circular and sustainable economy." }
    },
    bike: {
      pt: { title: "Mobilidade Sustentável com Bicicleta Elétrica", desc: "O projeto B2H2 não se limita à produção de hidrogênio; ele também demonstra várias possibilidades de usos, em aplicações práticas, promovendo a mobilidade urbana sustentável dentro do Centro Politécnico da UFPR, por exemplo. Bicicletas abastecidas com o hidrogênio de alta pureza, produzido na planta piloto, serão utilizadas para demonstração da tecnologia, sendo que o armazenamento do hidrogênio ocorrerá na forma de hidretos metálicos. Esta aplicação ilustra de forma tangível como a tecnologia de conversão de resíduos em H\u2082 e eletricidade pode ser integrada ao dia a dia, servindo como um modelo de estação de carregamento limpa e local que contribui para a redução da emissão de poluentes no transporte." },
      en: { title: "Sustainable Mobility with Electric Bicycle", desc: "The B2H2 project also demonstrates practical uses such as electric bicycles, promoting sustainable urban mobility within the Polytechnic Center of UFPR. Bicycles powered by high-purity hydrogen, produced at the pilot plant, will be used to demonstrate the technology, with hydrogen storage occurring in the form of metal hydrides. This application tangibly illustrates how the technology of converting waste into H\u2082 and electricity can be integrated into daily life, serving as a model for a clean and local charging station that helps reduce pollutant emissions in transport." }
    },
    automation: {
      pt: { title: "Processo Automatizado e Monitorado", desc: "A planta B2H2 é instrumentada com sensores, válvulas, medidores e atuadores, comandados por um Controlador Lógico Programável (CLP). A comunicação com o nível de supervisão ocorre via Ethernet para um servidor de dados desenvolvido em linguagem Python, responsável pela aquisição, validação e registro das variáveis de processo em banco de dados MySQL. O monitoramento e o controle em tempo real são realizados por um sistema supervisório via Web, complementado por uma IHM local que oferece recursos para operação por especialistas." },
      en: { title: "Automated and Monitored Process", desc: "The B2H2 plant is instrumented with sensors, valves, meters, and actuators, controlled by a Programmable Logic Controller (PLC). Communication with the supervisory level occurs via Ethernet to a data server developed in Python, responsible for acquiring, validating, and recording process variables in a MySQL database. Real-time monitoring and control are performed by a supervisory system via Web, complemented by a local HMI that provides resources for operation by specialists." }
    },
    ml: {
      pt: { title: "Supervisão com apoio de Inteligência Artificial", desc: "O sistema proposto integra um Sistema Especialista (SE) para recomendar ações de uso do equipamento e modelos de Aprendizado de Máquina (AM) para a identificação precoce de falhas, promovendo o uso adequado dos recursos, com economia e eficiência dos processos. A transmissão e persistência dos dados é uma inovação no contexto da reforma a seco, e representa a base para aplicações em Inteligência Artificial (IA), uma vez que não há IA sem dados de qualidade. Esses dados poderão ser aplicados em algoritmos de AM para geração de novos conhecimento e otimização dos processos." },
      en: { title: "Supervision with AI Support", desc: "The proposed system integrates an Expert System for recommendations on equipment use and Machine Learning models for early fault detection, promoting the proper use of resources, with economy and efficiency of processes. The transmission and persistence of data is an innovation in the context of dry reforming, and represents the basis for applications in Artificial Intelligence (AI), since there is no AI without quality data. This data can be applied in ML algorithms for generating new knowledge and optimizing processes." }
    },
    certificado: {
      pt: { title: "Metodologia de Certificação e Rastreabilidade para Hidrogênio de Baixo Carbono", desc: "A principal contribuição está na proposição de uma metodologia robusta e transparente para certificar o hidrogênio de baixo carbono produzido via reforma a seco de resíduos alimentares. O projeto inclui o desenvolvimento de uma calculadora de pegada de carbono baseada nas normas ISO 14040, 14044 e 14067:2023, permitindo a avaliação consistente dos fluxos de entrada e saída do processo produtivo. A ferramenta é prática, auditável e adequada a aplicações técnicas e de certificação. O diferencial está na integração da metodologia com rastreabilidade digital via blockchain, possibilitando a emissão de certificados digitais de conformidade e assegurando a integridade e imutabilidade dos dados, fortalecendo a confiança de stakeholders e compradores de hidrogênio sustentável." },
      en: { title: "Certification and Traceability Methodology for Low-Carbon Hydrogen", desc: "The main contribution is proposing a robust and transparent methodology to certify low-carbon hydrogen produced via dry reforming of food waste. The project includes developing a carbon footprint calculator based on ISO 14040, 14044, and 14067:2023 standards, allowing consistent evaluation of input and output flows of the production process. The tool is practical, auditable, and suitable for technical and certification applications. The differential is the integration of the methodology with digital traceability via blockchain, enabling the issuance of digital certificates of conformity and ensuring the integrity and immutability of data, strengthening the trust of stakeholders and buyers of sustainable hydrogen." }
    }
  };

  return (
    <div className="relative">
      <Navbar />
      {/* Hero Section */}
      <ParallaxSection id="hero" bgImage={heroImage} strength={0} className="pt-20">
        <h1 className="section-title bg-gradient-primary">{texts.hero[lang].title}</h1>
        <p className="section-subtitle" dangerouslySetInnerHTML={{ __html: texts.hero[lang].subtitle }} />
        <p className="section-description mt-6">{texts.hero[lang].desc}</p>
      </ParallaxSection>
      <VideoMiniPlayer />
      {/* Biomass Section */}
      <ParallaxSection id="biomassa" bgImage={biomassImage} strength={0}>
        <h2 className="section-title text-secondary">{texts.biomassa[lang].title}</h2>
        <p className="section-description">{texts.biomassa[lang].desc}</p>
      </ParallaxSection>

      {/* Biodigester Section */}
      <ParallaxSection id="biodigestor" bgImage={biodigesterImage} strength={0}>
        <h2 className="section-title text-primary">{texts.biodigestor[lang].title}</h2>
        <p className="section-description">{texts.biodigestor[lang].desc}</p>
      </ParallaxSection>

      {/* Syngas Section */}
      <ParallaxSection id="syngas" bgImage={syngasImage} strength={0}>
        <h2 className="section-title text-accent">{texts.syngas[lang].title}</h2>
        <p className="section-description">{texts.syngas[lang].desc}</p>
      </ParallaxSection>

      {/* PSA Section */}
      <ParallaxSection id="psa" bgImage={psaImage} strength={0}>
        <h2 className="section-title text-secondary">{texts.psa[lang].title}</h2>
        <p className="section-description">{texts.psa[lang].desc}</p>
      </ParallaxSection>

      {/* Fuel Cell Section */}
      <ParallaxSection id="fuelcell" bgImage={fuelCellImage} strength={0}>
        <h2 className="section-title text-primary">{texts.fuelcell[lang].title}</h2>
        <p className="section-description">{texts.fuelcell[lang].desc}</p>
      </ParallaxSection>

      {/* Amonia */}
      <ParallaxSection id="amonia" bgImage={amonia} strength={0}>
        <h2 className="section-title text-primary">{texts.amonia[lang].title}</h2>
        <p className="section-description">{texts.amonia[lang].desc}</p>
      </ParallaxSection>

      {/* Hydrogen Bike */}
      <ParallaxSection id="bike" bgImage={bike} strength={0}>
        <h2 className="section-title text-primary">{texts.bike[lang].title}</h2>
        <p className="section-description">{texts.bike[lang].desc}</p>
      </ParallaxSection>

      {/* Automation Section */}
      <ParallaxSection id="automation" bgImage={automationImage} strength={0}>
        <h2 className="section-title text-accent">{texts.automation[lang].title}</h2>
        <p className="section-description">{texts.automation[lang].desc}</p>
      </ParallaxSection>

      {/* AI/ML Section */}
      <ParallaxSection id="ml" bgImage={aiImage} strength={0}>
        <h2 className="section-title text-primary">{texts.ml[lang].title}</h2>
        <p className="section-description">{texts.ml[lang].desc}</p>
      </ParallaxSection>

      {/* Carbono/blockchain */}
      <ParallaxSection id="certificado" bgImage={certificadoImage} strength={0}>
        <h2 className="section-title text-primary">{texts.certificado[lang].title}</h2>
        <p className="section-description">{texts.certificado[lang].desc}</p>
      </ParallaxSection>
    </div>
  );
}